server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/reviews/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
