server:
  port: 9002

spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:postgresql://localhost:5432/cartdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
