server:
  port: 9001

spring:
  application:
    name: catalog-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/catalogdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
