server:
  port: 9004

spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: tu_correo@gmail.com
    password: tu_password_de_app
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
